name: Deploy MVS Electrical to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # 1. Get repository files
      - name: Checkout
        uses: actions/checkout@v6


      # 2. Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5


      # 3. Upload complete website
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'


      # 4. Deploy website
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
